server:
  port: 8087
spring:
  application:
    name: equipment-service
  datasource:
    url: jdbc:mysql://localhost:3306/equipment_management_system?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        file-extension: yml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.ngd.order.equipment.entity

logging:
  level:
    root: DEBUG
    edu.ngd.order.equipment: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
    java.sql: DEBUG
    com.zaxxer.hikari: DEBUG