server:
  port: 8089

spring:
  application:
    name: equipment-repair-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        file-extension: yml
    sentinel:
      transport:
        dashboard: localhost:8088
        eager: true
  datasource:
    url: jdbc:mysql://localhost:3306/equipment_management_system?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.ngd.order.equipment.repair.entity

logging:
  level:
    edu.ngd.order.equipment.repair.mapper: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG